version: "3.8"
services:
  db:
    image: postgres:15
    container_name: payslip_postgres
    environment:
      POSTGRES_USER: aghni
      POSTGRES_PASSWORD: root
      POSTGRES_DB: payslipdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
